spring.application.name=Portfolio

server.port=8080

spring.security.user.name=user
spring.security.user.password=ila7@Ila
spring.security.user.roles=ADMIN

spring.datasource.url=jdbc:postgresql://localhost:5432/ProjectManagerDB
spring.datasource.username=postgres
spring.datasource.password=ila7@Ila
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
